const Quentin_des = `Quentin Eichbaum was born and raised in Namibia and South Africa. He initially studied law at the University of Cape Town and then completed his MD, MPH, PhD/postdoctoral studies at Harvard Medical School and the Massachusetts Institute of Technology, and his residency and fellowship training at Massachusetts General Hospital (MGH) in Boston. He is currently Professor of Pathology, Microbiology and Immunology at Vanderbilt University Medical Center (VUMC) and Professor of Medical Education and Administration at Vanderbilt University School of Medicine. He serves on numerous national and international clinical, global health, education, and health humanities committees and boards.

In global health, he serves on the Board of Directors of the Consortium of Universities for Global Health (CUGH) and has chaired its Education Committee, Global Workforce Committee, and Global Health Humanities working group; and he is co-chair of the AFREhealth-CUGH Working Group (ACWG). He serves on the Education Committee of the FAIMER/ECFMG Board of Trustees. He also serves in leadership positions on several national and international health humanities committees and organizations.

In his clinical work, he chairs the AABB Global Transfusion Forum (GTF), the AABB Global Standards Committee, and the International Affairs Committee at ASFA. He is Medical Co-Director of Transfusion Medicine at VUMC, Director of the VUMC Transfusion Medicine Fellowship Program, Director of the Vanderbilt Pathology Program in Global Health, and Medical Director of the VA Tennessee Valley Health Care System Blood Bank. He co-founded and serves on the Executive Committee of CONSAMS.`;

const Saka_des = `Professor John D. Kalenga Saka is the Vice-Chancellor of Mzuzu University in Malawi. He has a PhD in Chemistry from University of East Anglia, United Kingdom and over 15 years of experience in University leadership and management and has published journal articles in high-impact journals and refereed Books. Professor Saka specialization is in food and agricultural chemistry. He is leads a University of six Faculties including Health Sciences and Science, Technology and Innovation. The University offers three programs: BSc (Nursing and Midwifery), BSc (Biomedical Science) and BSc (Optometry). The University is developing a Medical programs, which will be housed in the Faculty of Health Sciences.`;

const Penniecook_des = `Eustace A. Penniecook-Sawyers is an Associate Professor of Ophthalmology and a Retina and Vitreous Surgeon by profession.  He has been in the teaching realm for more than 20 years serving students of medicine, residents and fellows in their training. He is author of several academic articles in the area of ophthalmology. He has been involved in the development of medical training curriculums and inspection of the various school of medical institutions in Africa, Asia and the Americas, as an international inspector and evaluator for the Adventist Accrediting Association and the International Board of Education.

Dr. Penniecook currently works in Kigali, Rwanda where he serves as the Founding Dean for the Adventist School of Medicine for East-Central Africa; a faith-based institution that serves 11 countries for the Seventh Day Adventist Church. His role includes being the Principal of the Faculty of Health Sciences for the Adventist University of Central Africa.`;

const Maciel_des = `Dr. Maciel has worked for over 30 years in Agricultural research. Specialized in Reproductive Physiology and applied Animal Breeding, she worked on the Conservation of Indigenous breeds of cattle and goats, as well as other livestock species. As Senior Consultant/Coordinator and Regional Program Manager at the Community Investment Program of Anadarko and Regional Program Manager of Aga Khan Foundation, respectively, she has also large experience on the design, implementation, coordination and monitoring of community-based programs dealing with health, sanitation, education, agriculture/livestock, nutrition, etc. in rural areas. Within her livestock field experience, she was involved in the animal husbandry's curricula design and restructuring for the Higher polytechnic and medium agriculture schools. She worked for over 30 years in the Agriculture Research Institute of Mozambique, at the Center for Genetic Resources and Assisted Reproductive Technologies. Since December 2016, as a Deputy vice-chancellor for Academics of the Universidade Lúrio (UniLúrio), she has under her umbrella 7 faculties distributed in the 3 northern provinces of Mozambique, within which the Faculty of Health Sciences with 7 degree courses, including Medicine, as well as the Scientific and the Pedagogic Directorates. She is a member of the South African Society for Animal Science and of the Order of the Veterinarian Doctors of Mozambique. She has 10 peer review publications, several participations in Animal Science Congresses and several special reports, including policy documents on livestock development, being on the editor board of several journals (Elsevier) and external reviewer of animal science thesis for the University of the Free State.`;

const Falayi_des = ``;

const Christians_des = `Dr. Felicia Christians is a Family Physician and Public Health specialist and currently serves as the Associate Dean of the UNAM School of Medicine. She previously headed the Department of Family and Community Medicine at the UNAM, SoM, and has been instrumental in introducing Family Medicine into the undergraduate MBChB curriculum. She is currently working on the development of a Postgraduate Diploma in Family Medicine for Namibia via distance training which is for implementation in 2023.

She also works part-time in the Ministry of Health (MoHSS) as a clinician. This includes caring for patients with non-communicable diseases, especially diabetes, as well as coordinating the training of medical interns in primary care and family medicine. She is passionate about teaching and training and her aim is to further develop the UNAM School of Medicine to become a center of excellence in research, education, and clinical training that is locally relevant and globally competitive.`;

const Kamya_des = `Dorothy Kamya is an Assistant Professor and a practicing Consultant Anaesthetist at Aga Khan University Hospital in Nairobi.

She obtained her medical degree at University College, London in 1996 and became a fellow of the Royal College of Anaesthetists, FRCA (UK) in 2003. She is also a Fellow of the Higher Education Academy FHEA (UK) and during her fellowship training in anaesthesia at University College Hospital, London she was awarded the “Top Teacher” award from medical undergraduate students at University College Medical School, 2007/2008.

She obtained her Master's degree in Medical Education from Cardiff University in 2011 for which she received the dissertation prize and a distinction for her research study. She has been actively involved in the formulation and delivery of Training the Trainers courses in the UK, Europe and East Africa, specifically in conjunction with the World Federation of Societies of Anaesthesia (WFSA). She is an external examiner for the MHPE course at Makerere University, Kampala, Uganda.

Her role and responsibilities include the oversight postgraduate specialist medical training at Aga Khan University Hospital Nairobi and faculty development initiatives. Recently, she has been involved in the development and preparation phase for the launch of an undergraduate medical school at Aga Khan University, Nairobi.

Dorothy has a passion for supporting the development of emerging leaders in health. She is an alumnus of the Harvard Kennedy School Executive Leadership Program (2018) and she subsequently supported the Adaptive Leadership for Africa in the 21st Century course in Nairobi in 2019 as a Leadership Coach.   She is currently completing an executive MBA course.`

const Kafwamfwa_des = `BScHB - University of Zambia
MBCHB - University of Zambia
MCS (ECSA)
MMed (SGY) - University of Zambia`;

const Vainio_des = `Olli Vainio is currently working as a Special Advisor in the University of Turku, Finland. He has a long international career in working in different professional appointments as a researcher, visiting professor and professor in Switzerland (8 years) and in Finland. He has an extensive administrative experience (eg. Dean for Academic Affairs (Education) at the Faculty of Medicine, Oulu 2006-2013, Director of Degree Program on Medicine, Oulu University 2006-2017). He has participated in several European Union projects and activities in different roles 1998 - 2018. Vainio has published over 150 articles in international peer-reviewed journals. He has been an editor of APMIS (1997-2017) and an editor of Scandinavian Journal of Immunology since 2008. Lately (2011-2016) he has been a coordinator in capacity building programs funded by Finnish Ministry for Foreign Affairs in Africa (North-South-South (NSS) program I-STEP; Interprofessional Education promoting Public Health, 2011-2013 and MEDUNAM II, a HEI-ICI, 2013-2016). He is also a founding Member of the Consortium of New Sub-Saharan Africa Medical Schools (CONSAMS) in 2011.`;

export {
  Quentin_des,
  Saka_des,
  Penniecook_des,
  Maciel_des,
  Falayi_des,
  Christians_des,
  Kamya_des,
  Kafwamfwa_des,
  Vainio_des
}